import { Brain, Sparkles } from 'lucide-react'

/**
 * AiAnalysisPanel — displays the Llama 3.1 root cause explanation.
 * Props:
 *   explanation: string  — the LLM-generated text
 *   modelName:   string  — e.g. "llama3.1"
 *   isAnomaly:   boolean — controls panel styling
 */
export default function AiAnalysisPanel({ explanation, modelName = 'llama3.1', isAnomaly }) {
  const hasExplanation = explanation && explanation.trim().length > 0

  return (
    <div className={`
      glass rounded-2xl border overflow-hidden animate-fade-in transition-all duration-500
      ${isAnomaly && hasExplanation
        ? 'border-violet-500/35'
        : 'border-blue-500/15'}
    `}>
      {/* Header */}
      <div className={`
        flex items-center justify-between px-5 py-4 border-b border-slate-800/60
        ${isAnomaly && hasExplanation ? 'bg-violet-500/5' : ''}
      `}>
        <div className="flex items-center gap-2">
          <Brain className={`w-5 h-5 ${isAnomaly && hasExplanation ? 'text-violet-400' : 'text-blue-400'}`} />
          <span className="font-semibold text-white">AI Root Cause Analysis</span>
        </div>
        <div className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-violet-500/10 border border-violet-500/20 text-xs font-medium text-violet-400">
          <Sparkles className="w-3 h-3" />
          {modelName}
        </div>
      </div>

      {/* Content */}
      <div className="px-5 py-5">
        {hasExplanation ? (
          <div className="animate-slide-up">
            {/* Timestamp label */}
            <p className="text-xs text-slate-500 mb-3 flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-violet-500 animate-pulse inline-block" />
              Latest anomaly explanation
            </p>

            {/* Explanation text */}
            <div className={`
              relative p-4 rounded-xl text-sm leading-relaxed text-slate-300
              bg-violet-500/5 border border-violet-500/15
              before:absolute before:left-0 before:top-0 before:bottom-0 before:w-0.5
              before:rounded-full before:bg-violet-500/60
            `}>
              {explanation}
            </div>

            {/* Disclaimer */}
            <p className="text-xs text-slate-600 mt-3">
              Generated by {modelName} via Ollama — for informational purposes only.
            </p>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-8 text-center">
            <Brain className="w-10 h-10 text-slate-700 mb-3" />
            <p className="text-slate-500 text-sm font-medium">
              No anomaly explanation yet
            </p>
            <p className="text-slate-600 text-xs mt-1">
              {isAnomaly
                ? 'Llama 3.1 is analyzing…'
                : 'Analysis will appear when an anomaly is detected'}
            </p>
          </div>
        )}
      </div>
    </div>
  )
}
